version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=change_me_in_production
      - DATABASE_URL=sqlite:///survey_app.db
      - GUNICORN_WORKERS=2
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  # Uncomment to add a development service that uses Flask's development server
  # dev:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=development
  #     - SECRET_KEY=dev_secret_key
  #     - DATABASE_URL=sqlite:///survey_app.db
  #     - PORT=5000
  #   volumes:
  #     - .:/app
  #   restart: unless-stopped
